#pragma once

//
// SCENE SECTION
//
#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_ASSETS 1
#define SCENE_SECTION_OBJECTS 2

//
// GAME SECTION
//
#define GAME_SECTION_SETTINGS 1
#define GAME_SECTION_SCENES 2
#define GAME_SECTION_TEXTURES 3

//
// ASSET SECTION
//
#define ASSET_SECTION_UNKNOWN -1
#define ASSET_SECTION_SPRITES 1
#define ASSET_SECTION_ANIMATIONS 3

//
// OBJECT TYPES
//
#define OBJECT_TYPE_MARIO 0
#define OBJECT_TYPE_BRICK 1
#define OBJECT_TYPE_BULLET 2
#define OBJECT_TYPE_GOOMBA 3

//
// TEXTURE IDs
//
#define ID_TEX_BRICK 0
#define ID_TEX_MARIO 1
#define ID_TEX_MISC 2
#define ID_TEX_ENEMIES 3
#define ID_TEX_BBOX -100

//
// ANIMATION IDs
//
#define ID_ANI_BRICK 100
#define ID_ANI_BULLET 200

// BIG MARIO
#define ID_ANI_MARIO_BIG_IDLE_RIGHT 400
#define ID_ANI_MARIO_BIG_IDLE_LEFT 401
#define ID_ANI_MARIO_BIG_WALKING_RIGHT 500
#define ID_ANI_MARIO_BIG_WALKING_LEFT 501
#define ID_ANI_MARIO_BIG_RUNNING_RIGHT 600
#define ID_ANI_MARIO_BIG_RUNNING_LEFT 601
#define ID_ANI_MARIO_BIG_JUMP_WALK_RIGHT 700
#define ID_ANI_MARIO_BIG_JUMP_WALK_LEFT 701
#define ID_ANI_MARIO_BIG_JUMP_RUN_RIGHT 800
#define ID_ANI_MARIO_BIG_JUMP_RUN_LEFT 801
#define ID_ANI_MARIO_BIG_SIT_RIGHT 900
#define ID_ANI_MARIO_BIG_SIT_LEFT 901
#define ID_ANI_MARIO_BIG_BRACE_RIGHT 1000
#define ID_ANI_MARIO_BIG_BRACE_LEFT 1001

// SMALL MARIO
#define ID_ANI_MARIO_SMALL_IDLE_RIGHT 1100
#define ID_ANI_MARIO_SMALL_IDLE_LEFT 1102
#define ID_ANI_MARIO_SMALL_WALKING_RIGHT 1200
#define ID_ANI_MARIO_SMALL_WALKING_LEFT 1201
#define ID_ANI_MARIO_SMALL_RUNNING_RIGHT 1300
#define ID_ANI_MARIO_SMALL_RUNNING_LEFT 1301
#define ID_ANI_MARIO_SMALL_BRACE_RIGHT 1400
#define ID_ANI_MARIO_SMALL_BRACE_LEFT 1401
#define ID_ANI_MARIO_SMALL_JUMP_WALK_RIGHT 1500
#define ID_ANI_MARIO_SMALL_JUMP_WALK_LEFT 1501
#define ID_ANI_MARIO_SMALL_JUMP_RUN_RIGHT 1600
#define ID_ANI_MARIO_SMALL_JUMP_RUN_LEFT 1601

#define ID_ANI_MARIO_DIE 999

//GOOMBA
#define ID_ANI_GOOMBA_WALKING 3000
#define ID_ANI_GOOMBA_DIE 3001
