#pragma once
// Shim: redirect old-style includes to the refactored Mario class
#include "Objects/Player/Mario.h"

// Legacy macro aliases so old enemy/item code compiles unchanged
#define MARIO_LEVEL_SMALL    MARIO_LEVEL::SMALL
#define MARIO_LEVEL_BIG      MARIO_LEVEL::BIG
#define MARIO_LEVEL_FIRE     MARIO_LEVEL::FIRE
#define MARIO_LEVEL_FROG     MARIO_LEVEL::FROG
#define MARIO_LEVEL_RACCOON  3
#define MARIO_LEVEL_TANOOKI  MARIO_LEVEL::FROG
#define MARIO_LEVEL_HAMMER   5

#define MARIO_STATE_DIE             MARIO_STATE::DIE
#define MARIO_STATE_IDLE            MARIO_STATE::IDLE
#define MARIO_STATE_WALKING_RIGHT   MARIO_STATE::WALKING_RIGHT
#define MARIO_STATE_WALKING_LEFT    MARIO_STATE::WALKING_LEFT
#define MARIO_STATE_RUNNING_RIGHT   MARIO_STATE::RUNNING_RIGHT
#define MARIO_STATE_RUNNING_LEFT    MARIO_STATE::RUNNING_LEFT
#define MARIO_STATE_JUMP            MARIO_STATE::JUMP
#define MARIO_STATE_RELEASE_JUMP    MARIO_STATE::RELEASE_JUMP
#define MARIO_STATE_SIT             MARIO_STATE::SIT
#define MARIO_STATE_SIT_RELEASE     MARIO_STATE::SIT_RELEASE
#define MARIO_STATE_SHOOT           MARIO_STATE::SHOOT

#define MARIO_GRAVITY   MARIO_PARAMS::GRAVITY
#define MARIO_RUN_SPEED MARIO_PARAMS::RUN_SPEED
#define MARIO_WALK_SPEED MARIO_PARAMS::WALK_SPEED
#define MARIO_JUMP_SPEED MARIO_PARAMS::JUMP_SPEED
